[tool.poetry]
name = "mlops"
version = "0.1.0"
description = "Python 3 env."
authors = ["Ivan Mishalkin"]


[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.2.4"
jupyter = "^1.0.0"


[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"
